Customizing_Django_Templates/learning_site/courses/urls.py
from django.conf.urls import url

from .views import course_list, course_detail, step_detail

urlpatterns = [
    url(r'^$', course_list, name='list'),
    url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)/$', step_detail,
        name='step'),
    url(r'(?P<pk>\d+)/$', course_detail, name='detail'),
]

Customizing_Django_Templates/learning_site/learning_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import hello_world

urlpatterns = [
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', hello_world, name='hello'),
]

urlpatterns += staticfiles_urlpatterns()

Customizing_Django_Templates/learning_site/courses/models.py
from django.db import models


class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()
    
    def __str__(self):
        return self.title


class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    content = models.TextField(blank=True, default='')
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course)
    
    class Meta:
        ordering = ['order',]
    
    def __str__(self):
        return self.title

Customizing_Django_Templates/learning_site/courses/views.py
from django.shortcuts import get_object_or_404, render

from .models import Course, Step


def course_list(request):
    courses = Course.objects.all()
    email = 'questions@learning_site.com'
    return render(request, 'courses/course_list.html', {'courses': courses, 'email': email})


def course_detail(request, pk):
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course})


def step_detail(request, course_pk, step_pk):
    step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/step_detail.html', {'step': step})

Customizing_Django_Templates/learning_site/learning_site/views.py
from django.shortcuts import render


def hello_world(request):
    return render(request, 'home.html')

Customizing_Django_Templates/learning_site/courses/templates/courses/course_detail.html
{% extends "layout.html" %}

{% load humanize course_extras %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}
<article>
    <h2>{{ course.title }}</h2>
    {{ course.description|markdown_to_html }}

    <p>These are the {{ course.step_set.count|apnumber }} step{{ course.step_set.count|pluralize }} in this course: {{ course.step_set.all|join:", " }}</p>
    
    <section>
        {% for step in course.step_set.all %}
            <h3>
                <a href="{% url 'courses:step' course_pk=step.course.pk step_pk=step.pk %}">{{ step.title }}</a>
            </h3>
            {{ step.description }}
        {% endfor %}
    </section>
</article>
{% endblock %}

Customizing_Django_Templates/learning_site/courses/templates/courses/course_list.html
{% extends "layout.html" %}

{% load static from staticfiles %}

{% block title %}Available Courses{% endblock %}
{% block static %}<link rel="stylesheet" href="{% static 'courses/css/courses.css' %}">{% endblock %}

{% block content %}
<div class="cards">
    {% for course in courses %}
    <div class="card">
        <header><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></header>
        <div class="card-copy">
            {% if course.description|wordcount <= 5 %}
                {{ course.description }}
            {% else %}
                {{ course.description|truncatewords:5 }}
                <a href="{% url 'courses:detail' pk=course.pk %}">Read more</a>
            {% endif %}
            <div>Created on: {{ course.created_at|date:"m/d/y" }}</div>
        </div>
    </div>
    {% endfor %}
    <div>Have questions? Contact us! {{ email|urlize }}</div>
</div>
{% endblock %}

Customizing_Django_Templates/learning_site/courses/templates/courses/course_nav.html
{% for course in courses %}
    <div>
        <a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a>
    </div>
{% endfor %}

Customizing_Django_Templates/learning_site/courses/templates/courses/step_detail.html
{% extends "layout.html" %}

{% load course_extras %}

{% block title %}{{ step.title }} - {{ step.course.title }}{% endblock %}

{% block content %}
<article>
    <h2><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></h2>
    <h3>{{ step.title }}</h3>
    {% with con=step.content %}
        {{ con|linebreaks }}
        Content: {{ con|wordcount }} words. Estimated time to complete:
        {{ con|wordcount|time_estimate }} minute{{ con|wordcount|time_estimate|pluralize }}.
    {% endwith %}
</article>
{% endblock %}

Customizing_Django_Templates/learning_site/templates/home.html
{% extends "layout.html" %}

{% block title %}Well hello there!{% endblock %}

{% block content %}
    <h1>Welcome!</h1>
{% endblock %}

Customizing_Django_Templates/learning_site/templates/layout.html
{% load static from staticfiles %}
{% load course_extras %}

<!doctype html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/layout.css' %}">
        {% block static %}{% endblock %}
    </head>
    <body>
        <div class="site-container">
            <div>{% nav_courses_list %}</div>
            <nav>
                <a href="{% url 'hello' %}">Home</a>
                <a href="{% url 'courses:list' %}">Courses</a>
            </nav>
            <p>Don't miss out latest course, {% newest_course %}</p>
            {% block content %}{% endblock %}
        </div>
    </body>
</html>